### ISSUE TITLE
I am getting below error after integrating the library in my project.

### ISSUE THREAD

**Issue by MrVipinVijayan** [zhengxiaopeng/BounceProgressBar#2]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.vipin.pbdemo, PID: 7848
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vipin.pbdemo/com.example.vipin.pbdemo.MainActivity}: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class org.roc.bounceprogressbar.BounceProgressBar
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class org.roc.bounceprogressbar.BounceProgressBar
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                     at com.example.vipin.pbdemo.MainActivity.onCreate(MainActivity.java:11)
                                                     at android.app.Activity.performCreate(Activity.java:6285)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1137)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class org.roc.bounceprogressbar.BounceProgressBar
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                     at com.example.vipin.pbdemo.MainActivity.onCreate(MainActivity.java:11) 
                                                     at android.app.Activity.performCreate(Activity.java:6285) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1137) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.roc.bounceprogressbar.BounceProgressBar" on path: DexPathList[[zip file "/data/app/com.example.vipin.pbdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.vipin.pbdemo-1/lib/arm, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                     at com.example.vipin.pbdemo.MainActivity.onCreate(MainActivity.java:11) 
                                                     at android.app.Activity.performCreate(Activity.java:6285) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1137) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "org.roc.bounceprogressbar.BounceProgressBar" on path: DexPathList[[dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-support-annotations-25.1.0_dfba2c54963901e5b26c14ff81fe585fac7949ab-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.vipin.pbdemo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/
01-03 20:44:09.713 7848-7848/com.example.vipin.pbdemo I/Process: Sending signal. PID: 7848 SIG: 9

**Comment by MrVipinVijayan** [comment]
Sorry...accidently closed the issue...

**Comment by zhengxiaopeng** [comment]
You can disable  instant-run and rebuild... It's seem that problem caused by  instant-run.

**Comment by MrVipinVijayan** [comment]
Still not working

Regards
Vipin

**Comment by Sanjiv4** [comment]
I think the **package name** given is wrong. Try using 

**<org.rocko.bpb.BounceProgressBar**
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            bpb:shape="circle"
            bpb:singleSrcSize="10dp"
            bpb:speed="240"
            bpb:src="#6495ED" />

instead of

**<org.roc.bounceprogressbar.BounceProgressBar**
            xmlns:bpb="http://schemas.android.com/apk/res-auto"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:layout_centerVertical="true"
            bpb:shape="circle"
            bpb:singleSrcSize="8dp"
            bpb:speed="250"
            bpb:src="#6495ED" />

**Comment by zhengxiaopeng** [comment]
org.rocko.bpb.BounceProgressBar instead of org.roc.bounceprogressbar.BounceProgressBar.
close

**Comment by MrVipinVijayan** [comment]
Yeah. My friend only found it.
Please update the git.

Regards
Vipin
